Capstone Project I
dave-prog/Project-1 pull request #6
Opened 2023-03-17 20:23 UTC by dave-prog

## Capstone Project I
>This PR was created to give a detailed insight on the capstone project. The capstone project involved creating a website using all that has been learnt over the past 4 weeks using this [template](https://www.behance.net/gallery/29845175/CC-Global-Summit-2015) but tweaking its content to something personal. I built a tech summit page called WeCode Tech Summit using the template.

## 🛠Built Using:
- HTML
- CSS
- Javascript
- GitHub Flows
- Linters (Lighthouse, Webhint, StyleLint, ESLint)

## 📄Project's Features
- [x] Responsive design for all devices
- [x] Functional hamburger menu for small devices
- [x] Added some HTML content dynamically using Javascript

## 🔗Live Demo
The live demo of the website can be found [here](https://dave-prog.github.io/Project-1/)

2023-03-17 21:08 UTC, vickymarz requested changes
Hi @dave-prog , 

You have done a great job so far! 💪 👏
You still need to work on a few issues before moving on to the next project, but you're almost there!

## Top highlight 🎯

- The Pull Request is following the GitHub Flow ✅ 
- The PR title and description are professional and descriptive ✅ 
- The README is well documented ✅ 
- Linters are working properly ✅ 


## Required Changes ♻️

- [ ] This project requires you to provide a video presentation showcasing your website which you didn't add. Kindly add it 👍🏽 

![image](https://user-images.githubusercontent.com/63473584/226036422-3fbcd47c-b185-406f-8752-83c81230ca34.png)

- [ ] Kindly ensure that the README contains an "Acknowledgements" section or similar that gives appropriate credit to [Cindy Shin](https://www.behance.net/adagio07) the [author of the original design](https://www.behance.net/gallery/29845175/CC-Global-Summit-2015), as required by the [Creative Commons License](https://creativecommons.org/licenses/).

- [ ] I must commend the fact that you created several branches for the different functions of your app. I think it would be better if your branch name were more descriptive showcasing that you have finished the project something like `finish-project`, `conference-website`, `dev` can be better. Take note of these in the future. Well you will learn about `gitflow` and` github` flow more in the future 😄 

- [ ] Kindly ensure that your programs card on the mobile view are horizontally aligned to each other and not vertically aligned just as it is on the design. You can achieve this by using flexbox

your design 👇🏽 
![image](https://user-images.githubusercontent.com/63473584/226046095-038182b7-0560-41c0-9572-d4bac21f7dd5.png)

design guideline 👇🏽 
![image](https://user-images.githubusercontent.com/63473584/226046310-43c351ec-bc87-43ef-a294-36170cc71632.png)

- [ ] Kindly ensure that your  featured speakers on the mobile view are horizontally aligned to each other and not vertically aligned just as it is on the design. You can achieve this by using flexbox

design guideline 👇🏽 
![image](https://user-images.githubusercontent.com/63473584/226049093-d6890a96-b923-4893-811d-5217db3799c9.png)

your design 👇🏽 
![image](https://user-images.githubusercontent.com/63473584/226049582-63ce32e2-ccd1-4578-9824-b72d4a3ceef6.png)


_Check the comments under the review._
<img src="https://media2.giphy.com/media/Jq824R93JsLwZCaiSL/giphy.gif"/>

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

You can also consider:

N/A

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-03-17 21:08 UTC, vickymarz commented on index.html
>          </nav>
- [ ] You can do well to reduce the mobile view padding of your hero section to match the design guideline.

your design 👇🏽 
![image](https://user-images.githubusercontent.com/63473584/226047069-2fefe7e3-63a2-4acf-801b-e965b5696d2e.png)

design guideline 👇🏽 
![image](https://user-images.githubusercontent.com/63473584/226047390-c6b297a3-6a96-42e8-9a00-905f3b13ed6a.png)

2023-03-17 21:08 UTC, vickymarz commented on index.html
> +        <footer id="footer">
- [ ] Footer is currently missing on the homepage for mobile view. Kindly check it out and add it back 👍🏽

2023-03-17 21:24 UTC, dave-prog commented on index.html
> +        <footer id="footer">
This was the design requirement

2023-03-20 18:44 UTC, shella12 requested changes
Hi @dave-prog , 

Good job so far!
There are some issues that you still need to work on to prepare your project for the final evaluation but you are almost there!

<img src="https://media1.giphy.com/media/L422JoNlBBBD42zkQ9/giphy.gif"/>

## Suggested changes

- [ ] Great job 👍 on your project however please make sure to record at least five minutes video talking about the features of your website using [loom](https://www.loom.com/) also make sure to include the link to the recorded video in to your PR. The content of the video should include:

- A description of the project.
- A demo of the project features (different pages and different screen sizes).
- You should also highlight some interesting piece of code or something you built that you are very proud of.


- [ ] _Check the comments under the review._

You can use as many of my suggestions as you want. If there is anything you would like to skip - feel free to do that. However, I strongly recommend you to take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

2023-03-20 18:44 UTC, shella12 commented on about.html
> +                <img class="close" src="./assets/icons/close.png" alt="">
- [ ] Great job 👍 on adding descriptive `alt` tags on all your images. As you have already added `alt` tag for the close button image, you must have missed adding `alt ` description. I would suggest adding the description to the `alt `tag to make your site more accessible.

2023-03-20 18:44 UTC, shella12 commented on about.html
> +            </div>
- [ ] Your `partner section` is aligned really well in both desktop and mobile versions however instead of just encapsulating the `img` tags inside a `div` I suggest you use `ul` tag and in-list all images as a` li` tag as it would be semantically correct. 
 
The functional advantage is that `div`s mean little on their own, whereas `ul` `li`s explicitly mean "this is an un/ordered list of items." The term "semantics" refers to the way that you use the inherent meaning of existing structures to create explicit meaning.

2023-03-20 18:44 UTC, shella12 commented on index.html
> +                    <li><a href="#">Join</a></li>
- [ ] Please make sure to include link to the home page on your about page navbar, or logo to navigate back to the home page. You can change the link of `about page` to `home page` in the` about page` and vice versa

- [ ] Please also make sure the nabar links are working in the deployed version of your website

Your about page navbar:
<img width="381" alt="Screenshot 2023-03-20 at 10 51 18 PM" src="https://user-images.githubusercontent.com/44798044/226431879-341077c2-25d2-48c5-a5b2-3602f0e5a49f.png">

2023-03-20 18:44 UTC, shella12 commented on styles.css
> +  }
- [ ] Please make sure that your top nav with social icons and bottom navbar both are aligned like that in the behance [design guideline](https://www.behance.net/gallery/29845175/CC-Global-Summit-2015). as it is the [requirement](https://github.com/microverseinc/curriculum-html-css/blob/main/capstone/html_capstone.md#project-requirements) of the project to follow and maintain layout and positioning of elements

Your Design

<img width="1255" alt="Screenshot 2023-03-20 at 10 53 21 PM" src="https://user-images.githubusercontent.com/44798044/226433612-e50c24e9-e068-4447-8c91-76a487a812ac.png">


Design Guidelines


<img width="1033" alt="Screenshot 2023-03-20 at 10 48 34 PM" src="https://user-images.githubusercontent.com/44798044/226433978-208486c4-d4d7-4ffa-97a7-f8b89768d747.png">

2023-03-20 18:44 UTC, shella12 commented on about.html
> +                <hr>
- [ ] Please make your main heading of the about page bolder to make it look like design guideline for it is the[ requirement](https://github.com/microverseinc/curriculum-html-css/blob/main/capstone/html_capstone.md#project-requirements) of the project to follow fonts sizes and typography from the[ design guidelines](https://www.behance.net/gallery/29845175/CC-Global-Summit-2015)

Your design 

<img width="447" alt="Screenshot 2023-03-20 at 10 49 05 PM" src="https://user-images.githubusercontent.com/44798044/226435240-954f7c9c-42cc-47a8-930e-8e8902d3de54.png">

Design guideline

<img width="474" alt="Screenshot 2023-03-20 at 10 49 14 PM" src="https://user-images.githubusercontent.com/44798044/226435289-b0488329-0c6b-4623-8f1b-640f44d92bef.png">

2023-03-20 18:44 UTC, shella12 commented on about.html
> +        </section>
- [ ] Please make sure to include some paragraph description about the `logo` of the website into the` about page` `logo-section`

Your design 

<img width="356" alt="Screenshot 2023-03-20 at 10 47 34 PM" src="https://user-images.githubusercontent.com/44798044/226436192-f90e826a-a727-4f49-aee3-d1ebd7340903.png">

Design guidelines

<img width="468" alt="Screenshot 2023-03-20 at 11 42 50 PM" src="https://user-images.githubusercontent.com/44798044/226436455-ef79bfad-2abf-4f02-a513-0b4a3e40397d.png">

2023-03-22 22:38 UTC, dave-prog commented on about.html
> +            </div>
I avoided using the ul tag to minimize my css code

2023-03-23 09:29 UTC, Abenezer-Tilahun commented on about.html
> +                <hr>
Fixed.

2023-03-23 09:34 UTC, Abenezer-Tilahun commented on about.html
> +            </div>
- [ Optional ] As suggested by the previous reviewer  to make your code semantic correct kindly use `ul` tag and in-list all images as a` li` tag.

2023-03-23 09:34 UTC, Abenezer-Tilahun commented on index.html
> +                    <li><a href="#">Join</a></li>
Fixed.

2023-03-23 09:35 UTC, Abenezer-Tilahun commented on styles.css
> +  }
Fixed.

2023-03-23 09:35 UTC, Abenezer-Tilahun commented on about.html
> +                <hr>
Fixed.

2023-03-23 09:36 UTC, Abenezer-Tilahun commented on about.html
> +        </section>
Fixed.

2023-03-23 09:40 UTC, Abenezer-Tilahun approved these changes
Hi @dave-prog 
 
Your project is complete  👍 💯   There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

## Highlights 👏🏻

✔️ No linter errors.
✔️ You used correct Git Hub-Flow.
✔️ Professional README  
✔️ Good Commit Messages
✔️ Good job for Implemented Suggested changes.

## Optional suggestions 

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-03-23 09:40 UTC, Abenezer-Tilahun commented on README.md
> +>This is the [link](https://www.loom.com/share/0c95c306028b4970a7bb8f1bab6fc91c) to the video summarising what was accomplished during the project.
- [ Optional  ]  As stated in the project requirement when your document your project the record video length should be a maximum length of 5 minutes.But your video length is 12 minutes So for the future project kindly follow the project requirement.

2023-03-23 09:49 UTC, merged